services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "1883:1883"    # Puerto MQTT
      - "5672:5672"    # AMQP (opcional)
      - "15672:15672"  # Interfaz web de gestión
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secret
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins

volumes:
  rabbitmq_data: